[project]
name = "theclaude"
version = "0.1.0"
description = "🦾 The Claude - Claude Code File Recovery Tool. Like the claw from Toy Story, it reaches deep into conversation logs to rescue your files."
readme = "README.md"
requires-python = ">=3.13"
authors = [
    { name = "nickpending", email = "rudy@voidwire.info" }
]
keywords = ["claude", "recovery", "files", "cli", "tool"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Topic :: Utilities",
    "Topic :: System :: Archiving :: Backup",
]
dependencies = [
    "rich>=14.0.0",
    "typer>=0.16.0",
]

[project.scripts]
theclaude = "theclaude.cli:main"

[project.urls]
Homepage = "https://github.com/nickpending/theclaude"
Repository = "https://github.com/nickpending/theclaude.git"
Issues = "https://github.com/nickpending/theclaude/issues"

[dependency-groups]
dev = [
    "hatchling>=1.27.0",
    "mypy>=1.16.1",
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
    "ruff>=0.12.1",
]

[tool.uv]
package = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
